name: Daily Commit

on:
  schedule:
    - cron: '0 17 * * *'  # Exécute tous les jours à 17h UTC (Donc 18h en France car : France(Heure Hiver) = UTC+1 et France(Heure Été) = UTC+2)
  workflow_dispatch:  # Permet le déclenchement manuel

jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      - name: Cloner le dépôt
        uses: actions/checkout@v2

      - name: Configurer Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Spécifie la version de Python souhaitée

      - name: Installer les dépendances
        run: |
          python -m pip install --upgrade pip
          # Si tu as besoin d'installer des dépendances, tu peux le faire ici

      - name: Exécuter le script Python
        run: python commit_script.py

      - name: Configurer Git
        run: |
          git config --global user.name "${{ secrets.GIT_USER }}"
          git config --global user.email "${{ secrets.GIT_EMAIL }}"

      - name: Commit et Push
        run: |
          git add daily_update.txt
          git commit -m "Commit automatique - $(date +'%Y-%m-%d')"
          git push